[package]
name = "todo_games_server"
version = "0.1.0"
authors = ["Damien FERNANDES <damien.fernandes24@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
